sudo: false

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  - pip install --user hererocks
  - hererocks here -r^ --$LUA;
  - export PATH=$PATH:$PWD/here/bin

install:
  - luarocks make rockspecs/lua-llthreads2-compat-scm-0.rockspec
  - luarocks make rockspecs/lua-llthreads2-scm-0.rockspec

script: 
  - cd test
  - lua test_version.lua
  - lua test_table_copy.lua
  - lua test_threads.lua 10
  - lua test_llthreads.lua
  - lua test_join_timeout.lua
  - lua test_join_detach.lua
  - lua test_join_error.lua
  - lua test_register_ffi.lua
  - lua test_logger.lua
  - lua test_pass_cfunction.lua
  - lua test_load_llthreads2.lua
  - lua test_alive.lua
  - lua test_threads_ex.lua 10
  - lua test_threads_ex_arg.lua
  - lua test_threads_ex_opt.lua
  - lua test_threads_ex_opt_2.lua
  - lua test_threads_attr.lua
  - lua test_integer.lua
  # - lua$LUA_SFX test_register_llthreads.lua

notifications:
  email:
    on_success: change
    on_failure: always
